services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=netflix
    volumes:
      - ./data:/var/lib/postgresql/data

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
 
  api:
    build:
      dockerfile: Dockerfile
      context: "./netflix-api"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=netflix
      - JWT_SECRET='esto es muy secreto, en serio, creanme, confiad en mi, es 100% seguro'
      - STRIPE_SECRET_KEY=sk_test_51O5alyKk2TlgcK2ACQKvwv5Pq0Zeb9TO9lIMJXc8JfAMHgrObAkjI0qdquNP8Zu1nlr53QJX6P0rb698PkyOYj0L00oTUjEcj3
      - STRIPE_PRICE_ID_1=price_1PNM4SKk2TlgcK2ADbGG0EzA
      - STRIPE_PRICE_ID_2=price_1PNM52Kk2TlgcK2AhsQoIojW
      - STRIPE_PRICE_ID_3=price_1PNM6sKk2TlgcK2AJlDF4Iz7
  client:
    build:
      dockerfile: Dockerfile
      context: "./clone-netflix"
    environment:
      - PRODUCTION=false
      - DEVELOPMENT_URL=http://localhost:3003/
      - WEB_SOCKET_PROD_URL=ws://localhost/websocket

